name: 'Setup Terragrunt'
description: 'Installs Terragrunt using tgenv'
inputs:
  terragrunt_version_file:
    description: 'Path to the .terragrunt-version file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup tgenv
      shell: bash
      run: |
        git clone --depth=1 --branch main https://github.com/tgenv/tgenv.git ~/.tgenv
        echo "$HOME/.tgenv/bin" >> $GITHUB_PATH

    - name: Install Terragrunt
      shell: bash
      run: |
        TG_VERSION=$(cat ${{ inputs.terragrunt_version_file }})
        tgenv install $TG_VERSION
        tgenv use $TG_VERSION

    - name: Validate Terragrunt installation
      shell: bash
      run: terragrunt --version
