apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  goTemplate: true # Enables Go text/template engine
  generators:
    - git:
        repoURL: 'https://github.com/AMstyles/azure-aks-devops.git'
        revision: HEAD
        directories:
          - path: gitops/apps/**
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/AMstyles/azure-aks-devops.git'
        targetRevision: HEAD
        path: '{{ .path }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
