name: check-pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - "infra-tg/**"
      - ".github/workflows/check-pull-request.yaml"

permissions:
  contents: read
  id-token: write

env:
  TERRAGRUNT_WORKING_DIR: environments/prod
  TF_VERSION_FILE: .terraform-version
  TG_VERSION_FILE: .terragrunt-version

jobs:
  format-validation:
    name: Format & Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-tg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: ./.github/custom-actions/setup-terraform
        with:
          terraform_version_file: ${{ env.TF_VERSION_FILE }}

      - name: Setup Terragrunt
        uses: ./.github/custom-actions/setup-terragrunt
        with:
          terragrunt_version_file: ${{ env.TG_VERSION_FILE }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive modules

      - name: Terragrunt HCL Format Check
        run: terragrunt hcl fmt --check

  plan:
    name: Terragrunt Plan
    needs: format-validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-tg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: ./.github/custom-actions/setup-terraform
        with:
          terraform_version_file: ${{ env.TF_VERSION_FILE }}

      - name: Setup Terragrunt
        uses: ./.github/custom-actions/setup-terragrunt
        with:
          terragrunt_version_file: ${{ env.TG_VERSION_FILE }}

      - name: Azure Login (OIDC)
        uses: ./.github/custom-actions/azure-oidc-login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terragrunt Init & Plan
        run: |
          terragrunt run --all init --non-interactive \
            --working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

          terragrunt run --all plan --non-interactive \
            --working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"